In [5]:
def factorial(num):
    if num<0:
        return 0
    elif num == 0 or num ==1:
        return 1
    else:
        fact = 1
        while(num>1):
            fact = fact*num
            num-=1
        return fact
num = int(input("Enter the number"))
factorial(num)

Enter the number5


120

In [7]:
def factorial(n):
    return 1 if (n==1 or n==0) else n*factorial(n-1);
num = int(input("Enter the number"))
factorial(num)

Enter the number10


3628800

In [8]:
def factorial(n):
    res = 1
    for i in range(2,n+1):
        res *=i
    return res
num = int(input("Enter the number"))
factorial(num)

Enter the number5


120

In [9]:
import numpy as np
n = int(input("Enter the number"))
x = np.prod([i for i in range(1,n+1)])
print(x)

Enter the number5
120


In [13]:
# Simple interest
def simple_interest(p,t,r):
    print('The principle is',p)
    print('The time period is',t)
    print('The rate of interest is',)
# formula si = (p*t*r)/100
    si =(p*t*r)/100
    return si
simple_interest(5,6,7)

The principle is 5
The time period is 6
The rate of interest is


2.1

In [14]:
# 0 1 0 1 0 1 0 1 
# 1 0 1 0 1 0 1 0 
# 0 1 0 1 0 1 0 1 
# 1 0 1 0 1 0 1 0 
# 0 1 0 1 0 1 0 1 
# 1 0 1 0 1 0 1 0 
# 0 1 0 1 0 1 0 1 
# 1 0 1 0 1 0 1 0
import numpy as np
 
# function to print Checkerboard pattern
def printcheckboard(n):
     
    print("Checkerboard pattern:")
 
    # create a n * n matrix
    x = np.zeros((n, n), dtype = int)
 
    # fill with 1 the alternate rows and columns
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1
     
    # print the pattern
    for i in range(n):
        for j in range(n):
            print(x[i][j], end =" ")
        print()
 
 
# driver code
n = 8
printcheckboard(n)

Checkerboard pattern:
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


In [15]:
import numpy as np
def printcheckboard(n):
    final = []
    for i in range(n):
        final.append(list(np.tile([0,1],int(n/2))) if i%2==0 else list(np.tile([1,0],int(n/2))))
    print(np.array(final))
 
 
# driver code
n = 8
printcheckboard(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [16]:
# determining the size of the heart
size = 15
 
# printing the inverted triangle
for a in range(0, size):
    for b in range(a, size):
        print(" ", end = "")
    for b in range(1, (a * 2)):
        print("*", end = "")
    print("")
 
# printing rest of the heart
for a in range(size, int(size / 2) - 1 , -2):
 
    # printing the white space right-triangle
    for b in range(1, size - a, 2): 
        print(" ", end = "")
 
    # printing the first trapezium
    for b in range(1, a + 1):
        print("*", end = "")
 
    # printing the white space triangle
    for b in range(1, (size - a) + 1):
        print(" ", end = "")
 
    # printing the second trapezium
    for b in range(1, a):
        print("*", end = "")
 
    # new line
    print("")

               
              *
             ***
            *****
           *******
          *********
         ***********
        *************
       ***************
      *****************
     *******************
    *********************
   ***********************
  *************************
 ***************************
*****************************
 *************  ************
  ***********    **********
   *********      ********
    *******        ******


In [17]:
def pattern(n):
 
    # traverse through the elements
    # in n assuming it as a string
    for i in n:
 
        # print | for every line
        print("|", end = "")
 
        # print i number of * s in
        # each line
        print("*" * int(i))
 
# get the input as string        
n = "41325"
pattern(n)

|****
|*
|***
|**
|*****


In [18]:
n = 41325
x = []
while n>0:
    x.append(n%10)
    n //= 10
for i in range(len(x)-1,-1,-1):
    print('|'+x[i]*'*')

|****
|*
|***
|**
|*****


In [19]:
# Compund interest
# A = P(1 + R/100) t 

# Compound Interest = A – P 

# Where, 
# A is amount 
# P is the principal amount 
# R is the rate and 
# T is the time span

def compound_interest(principle, rate, time):
 
    # Calculates compound interest
    Amount = principle * (pow((1 + rate / 100), time))
    CI = Amount - principle
    print("Compound interest is", CI)
 
 
# Driver Code
compound_interest(10000, 10.25, 5)

Compound interest is 6288.946267774416


In [20]:
# # Armstrong number:
# Input : 153
# Output : Yes
# 153 is an Armstrong number.
# 1*1*1 + 5*5*5 + 3*3*3 = 153
# abcd... = pow(a,n) + pow(b,n) + pow(c,n) + pow(d,n) + .... 
def power(x, y):
     
    if y == 0:
        return 1
    if y % 2 == 0:
        return power(x, y // 2) * power(x, y // 2)
         
    return x * power(x, y // 2) * power(x, y // 2)
 
# Function to calculate order of the number
def order(x):
 
    # Variable to store of the number
    n = 0
    while (x != 0):
        n = n + 1
        x = x // 10
         
    return n
 
# Function to check whether the given
# number is Armstrong number or not
def isArmstrong(x):
     
    n = order(x)
    temp = x
    sum1 = 0
     
    while (temp != 0):
        r = temp % 10
        sum1 = sum1 + power(r, n)
        temp = temp // 10
 
    # If condition satisfies
    return (sum1 == x)
 
# Driver code
x = 153
print(isArmstrong(x))
 
x = 1253
print(isArmstrong(x))

True
False


In [21]:
n = 153  # or n=int(input()) -> taking input from user
s = n  # assigning input value to the s variable
b = len(str(n))
sum1 = 0
while n != 0:
    r = n % 10
    sum1 = sum1+(r**b)
    n = n//10
if s == sum1:
    print("The given number", s, "is armstrong number")
else:
    print("The given number", s, "is not armstrong number")
 

The given number 153 is armstrong number
